// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=../mocks/mock_workflow.go -package=mocks ExecutorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecutorInterface is a mock of ExecutorInterface interface.
type MockExecutorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorInterfaceMockRecorder
	isgomock struct{}
}

// MockExecutorInterfaceMockRecorder is the mock recorder for MockExecutorInterface.
type MockExecutorInterfaceMockRecorder struct {
	mock *MockExecutorInterface
}

// NewMockExecutorInterface creates a new mock instance.
func NewMockExecutorInterface(ctrl *gomock.Controller) *MockExecutorInterface {
	mock := &MockExecutorInterface{ctrl: ctrl}
	mock.recorder = &MockExecutorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorInterface) EXPECT() *MockExecutorInterfaceMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutorInterface) Execute(ctx context.Context, workflowName string, input []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, workflowName, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorInterfaceMockRecorder) Execute(ctx, workflowName, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutorInterface)(nil).Execute), ctx, workflowName, input)
}
